# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Build and Deploy to Release Branch

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: 22.x
        
    - name: Install dependencies
      run: npm install

    - name: Build project
      run: npm run build:prod
    
    - name: Deploy to release branch
      run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git checkout --orphan release  # Tạo branch release (nếu chưa có)
          git rm -rf .  # Xóa tất cả file hiện tại
          mv dist/* .  # Di chuyển nội dung của dist lên root
          rm -rf dist  # Xóa thư mục dist (không cần thiết nữa)
          git add .
          git commit -m "Deploy latest build"
          git push --force origin release  # Ghi đè branch release
